repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-json
      - id: check-added-large-files
      - id: check-yaml
      - id: check-merge-conflict
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.16.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies:
          - "@team23/commitlint-config@1.0.0"
default_stages:
  - commit
default_install_hook_types:
  - pre-commit
  - commit-msg
