import type { Linter } from 'eslint';
import stylistic from '@stylistic/eslint-plugin';

const maxLength = 140;
const stylisticConfig: Linter.Config = {
    name: 'team23/java-script/stylisticJs/optional',
    plugins: {
        '@stylistic': stylistic,
    },
    rules: {
        '@stylistic/array-bracket-newline': ['error', 'consistent'],
        '@stylistic/array-bracket-spacing': 'error',
        '@stylistic/array-element-newline': ['error', 'consistent'],
        '@stylistic/arrow-parens': ['error', 'as-needed'],
        '@stylistic/arrow-spacing': 'error',
        '@stylistic/block-spacing': 'error',
        '@stylistic/brace-style': ['error', '1tbs', { allowSingleLine: true }],
        '@stylistic/comma-dangle': ['error', 'always-multiline'],
        '@stylistic/comma-spacing': 'error',
        '@stylistic/comma-style': 'error',
        '@stylistic/computed-property-spacing': ['error', 'never'],
        '@stylistic/eol-last': 'error',
        '@stylistic/func-call-spacing': 'error',
        '@stylistic/function-call-argument-newline': ['error', 'consistent'],
        '@stylistic/function-call-spacing': 'error',
        '@stylistic/function-paren-newline': ['error', 'consistent'],
        '@stylistic/generator-star-spacing': 'error',
        '@stylistic/implicit-arrow-linebreak': 'error',
        // may cause performance issues with large codebase
        '@stylistic/indent': 'off',
        '@stylistic/jsx-quotes': 'error',
        '@stylistic/key-spacing': 'error',
        '@stylistic/keyword-spacing': 'error',
        '@stylistic/line-comment-position': 'error',
        '@stylistic/linebreak-style': 'error',
        '@stylistic/lines-around-comment': 'error',
        '@stylistic/max-len': [
            'error',
            maxLength,
        ],
        '@stylistic/max-statements-per-line': 'error',
        '@stylistic/multiline-comment-style': 'off',
        '@stylistic/multiline-ternary': ['error', 'always-multiline'],
        '@stylistic/new-parens': 'error',
        '@stylistic/newline-per-chained-call': 'error',
        '@stylistic/no-confusing-arrow': 'error',
        '@stylistic/no-extra-parens': 'error',
        '@stylistic/no-extra-semi': 'error',
        '@stylistic/no-floating-decimal': 'error',
        '@stylistic/no-multi-spaces': 'error',
        '@stylistic/no-multiple-empty-lines': 'error',
        '@stylistic/no-tabs': 'error',
        '@stylistic/no-trailing-spaces': 'error',
        '@stylistic/no-whitespace-before-property': 'error',
        '@stylistic/object-curly-newline': 'error',
        '@stylistic/object-curly-spacing': ['error', 'always'],
        '@stylistic/object-property-newline': ['error', { allowAllPropertiesOnSameLine: true }],
        '@stylistic/operator-linebreak': 'error',
        '@stylistic/padding-line-between-statements': 'error',
        '@stylistic/quote-props': ['error', 'as-needed'],
        '@stylistic/quotes': ['error', 'single'],
        '@stylistic/rest-spread-spacing': 'error',
        '@stylistic/semi': ['error', 'always'],
        '@stylistic/semi-spacing': 'error',
        '@stylistic/semi-style': 'error',
        '@stylistic/space-before-blocks': 'error',
        '@stylistic/space-before-function-paren': [
            'error',
            {
                anonymous: 'never',
                named: 'never',
                asyncArrow: 'always',
            },
        ],
        '@stylistic/space-in-parens': 'error',
        '@stylistic/space-infix-ops': ['error', { int32Hint: true }],
        '@stylistic/space-unary-ops': 'error',
        '@stylistic/spaced-comment': 'error',
        '@stylistic/switch-colon-spacing': 'error',
        '@stylistic/template-curly-spacing': ['error', 'always'],
        '@stylistic/wrap-regex': 'error',
        '@stylistic/yield-star-spacing': 'error',
    },
};

export default [stylisticConfig];
