name: Deploy
on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      env:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC
      contents: read
    environment: ${{ inputs.env }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check version changes
        uses: EndBug/version-check@v2.1.5
        id: check
        with:
          diff-search: true
          file-name: ${{ inputs.package }}/package.json
      - name: Set up Node.js for NPM
        if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      - name: Update npm
        if: steps.check.outputs.changed == 'true'
        run: npm install -g npm@latest
      - name: Install global dependencies
        if: steps.check.outputs.changed == 'true'
        run: npm ci
      - name: Install package dependencies
        if: steps.check.outputs.changed == 'true'
        run: cd ${{ inputs.package }} && npm ci
      - name: Build package
        if: steps.check.outputs.changed == 'true'
        run: cd ${{ inputs.package }} && npx --yes nx build --excludeTaskDependencies
      - name: Publish
        if: steps.check.outputs.changed == 'true'
        run: cd ${{ inputs.package }} && npm publish --provenance --access public
