name: Publish JavaScript
on:
  push:
    branches:
      - main
    paths:
      - libs/java-script/package.json

jobs:
  deploy-java-script:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      package: libs/java-script
